---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-public
spec:
  destination:
    name: smaug
    namespace: opf-grafana-public
  project: operate-first
  source:
    path: grafana/overlays/moc/smaug-public
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
