---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kfp-tekton
spec:
  destination:
    name: smaug
    namespace: kubeflow
  project: operate-first
  source:
    path: kfp-tekton/overlays/moc/smaug
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
