---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meteor-shower
spec:
  destination:
    name: smaug
    namespace: aicoe-meteor
  project: operate-first
  source:
    path: manifests
    repoURL: https://github.com/AICoE/meteor
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
