apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: thanos-objectstorage-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: thanos-objectstorage-secret
  dataFrom:
    - extract:
        key: moc/smaug/opf-observatorium/thanos-objectstorage-secret
