apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry-collector-operator
resources:
  - ../../base/core/namespaces/opentelemetry-collector-operator
  - ../../base/operators.coreos.com/subscriptions/opentelemetry-collector-operator
  - ../../base/operators.coreos.com/operatorgroups/opentelemetry-collector-operator
