apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: argocd-notifications-secret
  dataFrom:
    - extract:
        key: moc/infra/argocd/argocd-notifications-secret
