apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openmetadata
resources:
- ../../base/openmetadata-dependencies
- ../../base/openmetadata
- secret

patchesStrategicMerge:
  - patches/deployments/openmetadata.yaml
  - patches/configmaps/openmetadata-dependencies-config-envs.yaml
