apiVersion: kustomize.config.k8s.io/v1beta1
components:
- ../../../../components/project-admin-rolebindings/operate-first
- ../../../../components/monitoring-rbac
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/medium
kind: Kustomization
namespace: opf-grafana-public
resources:
- namespace.yaml
