apiVersion: v1
kind: ResourceQuota
metadata:
  name: opf-trino-custom
spec:
  hard:
    limits.cpu: '40'
    limits.memory: 100Gi
    requests.cpu: '20'
    requests.memory: 80Gi
    requests.storage: 20Gi
    count/objectbucketclaims.objectbucket.io: 1
