apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dotenv
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: dotenv
  dataFrom:
    - extract:
        key: osc/osc-cl2/kepler-monitoring/dotenv
