@Library('kyverno-parallel-apply@test/integration') _

def cliVersion = "1.0.1"
def cliFile = "kustomtrace-cli-${cliVersion}-all.jar"
def cliUrl = "https://github.com/zucca-devops-tooling/kustom-trace/releases/download/v${cliVersion}/${cliFile}"
def appListFile = "apps.yaml"
def builtAppsFolder = "kustomize-output"
def policiesFile = "policies.yaml"
def kyvernoResults = "results.yaml"

pipeline {
    agent any

    environment {
        GRADLE_OPTS = '-Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Download kustom-trace-cli') {
            steps {
                script {
                    sh "curl -LO ${cliUrl}"
                }
            }
        }
        stage('Get apps to build') {
            steps {
                script {
                    sh "java -jar ${cliFile} -a ./kubernetes -o ${appListFile} list-root-apps"
                }
            }
        }
        stage('Build apps') {
            steps {
                script {
                    def apps = readYaml file: appListFile
                    sh "mkdir ${builtAppsFolder}"

                    if (apps && apps.'root-apps') {
                        apps.'root-apps'.each { appPath ->
                            def outputFile = builtAppsFolder + "/" + appPath.replaceAll("/", "_") + ".yaml"
                            echo "--- Executing build for: ${appPath} ---"
                            def buildResult = sh(
                                script: "kustomize build kubernetes/${appPath} -o ${outputFile}",
                                returnStatus: true
                            )

                            if (buildResult != 0) {
                                echo "❌ Failed to build ${appPath}, skipping..."
                            }
                        }
                    }
                }
            }
        }
        stage('Build kyverno policies') {
            steps {
                script {
                    sh "kustomize build ./policies -o ${policiesFile}"
                }
            }
        }/*
        stage('Add extra autogenerated resources') {
            steps {
                script {
                    sh "chmod +x generate-expensive-apps.sh"
                    sh "./generate-expensive-apps.sh"
                }
            }
        }*/
        /*
        stage('Apply kyverno policies') {
            steps {
                script {
                    try {
                        sh "kyverno apply ${policiesFile} --resource ${builtAppsFolder} --audit-warn --policy-report --output generated > ${kyvernoResults}"
                    } catch (e) {
                        println "Kyverno policies failed"
                    }
                }
            }
            post {
                always {
                    script {
                        sh "mkdir generated"
                        if (fileExists(kyvernoResults)) {
                            archiveArtifacts artifacts: "${kyvernoResults}"
                        }
                        sh "ls generated"
                    }
                }
            }
        }*/
        stage('Parallel Apply') {
            steps {
                script {
                    sh "mkdir generated"
                    kyvernoParallelApply([
                        'generatedResourcesDir': 'generated',
                        'manifestSourceDirectory': builtAppsFolder,
                        'finalReportPath': kyvernoResults,
                        'policyPath': policiesFile
                    ])
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
