apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmetadata
spec:
  template:
    spec:
      volumes:
        - name: logs
          emptyDir: {}
      containers:
        - name: openmetadata
          volumeMounts:
            - mountPath: /openmetadata-0.12.0/logs
              name: logs
          envFrom:
            - secretRef:
                name: openmetadata-envs
          env:
            - name: AIRFLOW_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_USERNAME
            - name: AIRFLOW_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_PASSWORD
            - name: DB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: OPENMETADATA_DB_PASSWORD
            - name: AIRFLOW_HOST
              value: "http://airflow.$YOUR_NAMESPACE.svc.cluster.local:8080"
            - name: SERVER_HOST_API_URL
              value: "http://openmetadata.$YOUR_NAMESPACE.svc.cluster.local:8585/api"
