apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resourcequota.yaml
namespace: physrisk-resilience
components:
  - ../../../../components/limitranges/default
  - ../../../../components/project-admin-rolebindings/physrisk
