apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: okd-team
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'okd-*'
      server: 'https://api.smaug.na.operate-first.cloud:6443'
    - namespace: 'kvm-device-plugin'
      server: 'https://api.smaug.na.operate-first.cloud:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:okd-team:project-admin, applications, get, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, create, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, update, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, delete, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, sync, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, override, okd-team/*, allow
        - p, proj:okd-team:project-admin, applications, action/*, okd-team/*, allow
      groups:
        - okd-team
