apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tremor-demo
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'tremor-demo*'
      name: 'smaug'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:tremor-demo:project-admin, applications, get, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, create, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, update, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, delete, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, sync, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, override, tremor-demo/*, allow
        - p, proj:tremor-demo:project-admin, applications, action/*, tremor-demo/*, allow
      groups:
        - tremor-demo
        - operate-first
