apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: prow
  title: Prow
  description: Prow is a Kubernetes based CI/CD system. Additionally Prow provides GitHub automation in the form of policy enforcement, chat-ops, and automatic PR merging.
  annotations:
    operate-first.cloud/featured: "true"
    operate-first.cloud/logo-url: https://prow.operate-first.cloud/static/logo-light.png
    backstage.io/kubernetes-label-selector: "app.kubernetes.io/component=prow"
    github.com/project-slug: operate-first/apps
    argocd/app-name: ci-prow-prod-smaug
  links:
    - url: https://prow.operate-first.cloud/
      title: Prow dashboard
      icon: web
    - url: https://github.com/kubernetes/test-infra/blob/f7e21a3c18f4f4bbc7ee170675ed53e4544a0632/docs/architecture.dot
      title: Architecture diagram
      icon: web
    - url: https://github.com/operate-first/apps/tree/master/prow
      title: Configuration
      icon: web
    - url: https://raw.githubusercontent.com/kubernetes/test-infra/master/prow/docs/pr-interactions-sequence.svg?sanitize=true
      title: PR interaction sequence
      icon: web
spec:
  owner: group:operate-first
  domain: sre
