apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-annotations-exporter
  labels:
    app: k8s-annotations-exporter
spec:
  selector:
    matchLabels:
      app: k8s-annotations-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-annotations-exporter
    spec:
      serviceAccountName: k8s-annotations-exporter
      containers:
        - name: k8s-annotations-exporter
          image: quay.io/4n4nd/k8s-annotations-exporter:latest
          command:
            - k8s_annotations_exporter
          args:
            - '-vv'
            - '--in-cluster'
            - '--http-server-port=8000'
            - '--metrics-refresh-interval=300'
            - '--resource-api-version=v1'
            - '--resource-kind=Namespace'
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 50Mi
          ports:
            - containerPort: 8000
              name: metrics
