---
apiVersion: v1
kind: Service
metadata:
  name: k8s-annotations-exporter
  labels:
    app: k8s-annotations-exporter
spec:
  selector:
    app: k8s-annotations-exporter
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      name: metrics
