apiVersion: v1
kind: ResourceQuota
metadata:
  name: opf-ci-pipelines-custom
spec:
  hard:
    limits.cpu: '24'
    limits.memory: 80Gi
    requests.cpu: '24'
    requests.memory: 80Gi
    requests.storage: 30Gi
    count/taskruns.tekton.dev: 3k
    count/objectbucketclaims.objectbucket.io: 1
