apiVersion: v1
kind: Namespace
metadata:
    name: debezium-ui
    annotations:
        openshift.io/display-name: Debezium UI
        openshift.io/requester: debezium
        op1st/project-owner: debezium
        op1st/onboarding-issue: "https://github.com/operate-first/support/issues/304"
        op1st/docs: "https://debezium.io/"
