apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: shared-secret
  dataFrom:
    - extract:
        key: osc/osc-cl2/odh-trino/shared-secret
