apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: identitatem-github-client-secret
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: identitatem-github-client-secret
  dataFrom:
    - extract:
        key: moc/infra/idp-auth-primary/identitatem-github-client-secret
