apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: crc-provisioning-vlan-ctrl-0
spec:
  nodeSelector:
    kubernetes.io/hostname: os-ctrl-0
  desiredState:
    interfaces:
      - name: eno1.307
        description: crc cluster provisioning network
        type: vlan
        state: up
        vlan:
          base-iface: eno1
          id: 307
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.22.1.250
              prefix-length: 24
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: crc-provisioning-vlan-ctrl-1
spec:
  nodeSelector:
    kubernetes.io/hostname: os-ctrl-1
  desiredState:
    interfaces:
      - name: eno1.307
        description: crc cluster provisioning network
        type: vlan
        state: up
        vlan:
          base-iface: eno1
          id: 307
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.22.1.251
              prefix-length: 24
---
apiVersion: nmstate.io/v1beta1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: crc-provisioning-vlan-ctrl-2
spec:
  nodeSelector:
    kubernetes.io/hostname: os-ctrl-2
  desiredState:
    interfaces:
      - name: eno1.307
        description: crc cluster provisioning network
        type: vlan
        state: up
        vlan:
          base-iface: eno1
          id: 307
        ipv4:
          enabled: true
          dhcp: false
          address:
            - ip: 172.22.1.252
              prefix-length: 24
