---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: centos
  namespace: okd-centos
spec:
  lookupPolicy:
    local: true
  tags:
    - name: stream8
      from:
        kind: DockerImage
        name: quay.io/centos/centos:stream8
      importPolicy:
        scheduled: true
    - name: stream9
      from:
        kind: DockerImage
        name: quay.io/centos/centos:stream9
      importPolicy:
        scheduled: true
