kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: web-terminal-service-catalog
resources:
- namespace.yaml
components:
- ../../../../components/limitranges/default
- ../../../../components/project-admin-rolebindings/service-catalog
- ../../../../components/resourcequotas/medium
