apiVersion: kustomize.config.k8s.io/v1beta1
components:
    - ../../../../components/limitranges/default
    - ../../../../components/resourcequotas/medium
    - ../../../../components/project-admin-rolebindings/okd-team
kind: Kustomization
namespace: okd-centos
resources:
    - namespace.yaml
