apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: kepler-metrics
  namespace: kafka
spec:
  config: {}
  partitions: 1
  replicas: 3
  topicName: kepler-metrics
