---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/component: store-index-cache
  app.kubernetes.io/version: 1.6.12-alpine
resources:
  - service.yaml
  - statefulset.yaml
