apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/component: store-index-cache
  name: observatorium-thanos-store-index-cache-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: store-index-cache
  serviceName: observatorium-thanos-store-index-cache-memcached
  template:
    metadata:
      labels:
        app.kubernetes.io/component: store-index-cache
    spec:
      containers:
      - args:
        - -m 2048
        - -I 5m
        - -c 3072
        - -v
        image: docker.io/memcached:1.6.12-alpine
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        resources:
          limits:
            cpu: "3"
            memory: 3Gi
          requests:
            cpu: 500m
            memory: 2558Mi
        terminationMessagePolicy: FallbackToLogsOnError
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: docker.io/prom/memcached-exporter:v0.9.0
        name: exporter
        ports:
        - containerPort: 9150
          name: metrics
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 50Mi
