apiVersion: v1
kind: ResourceQuota
metadata:
  name: opf-ci-pipelines-custom
spec:
  hard:
    limits.cpu: '16'
    limits.memory: 36Gi
    requests.cpu: '16'
    requests.memory: 36Gi
    requests.storage: 30Gi
    count/objectbucketclaims.objectbucket.io: 2
