apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ksops-pgp-key
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: ksops-pgp-key
  dataFrom:
    - extract:
        key: moc/infra/argocd/ksops-pgp-key
