apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    app.kubernetes.io/instance: cluster-resources-osc-cl2
    machineconfiguration.openshift.io/role: osc-platform
  name: 60-worker-kubeconfig-pid-limit
spec: {}
