---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: observatorium-thanos-receive-default
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: observatorium-thanos-receive-default
    apiVersion: apps/v1
  minReplicas: 7
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
