---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: thanos-receive-oauth-proxy
spec:
  scaleTargetRef:
    kind: Deployment
    name: thanos-receive-oauth-proxy
    apiVersion: apps/v1
  minReplicas: 3
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
