apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clo-kafka
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: clo-kafka
    template:
      engineVersion: v2
      data:
        ca-bundle.crt: '{{ index . "ca-bundle.crt" }}'
        tls.crt: '{{ index . "tls.crt" }}'
        tls.key: '{{ index . "tls.key" }}'
        user.p12: '{{ index . "user.p12" | b64dec }}'
        user.password: '{{ index . "user.password" }}'
  dataFrom:
    - extract:
        key: moc/smaug/opf-observatorium/clo-kafka
