apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resource-1.yaml
  - resource-2.yaml
  - resource-3.yaml
  - resource-4.yaml
  - resource-5.yaml
  - resource-6.yaml
  - resource-7.yaml
  - resource-8.yaml
  - resource-9.yaml
  - resource-10.yaml
  - resource-11.yaml
  - resource-12.yaml
  - resource-13.yaml
  - resource-14.yaml
  - resource-15.yaml
  - resource-16.yaml
  - resource-17.yaml
  - resource-18.yaml
  - resource-19.yaml
  - resource-20.yaml
  - resource-21.yaml
  - resource-22.yaml
  - resource-23.yaml
  - resource-24.yaml
  - resource-25.yaml
  - resource-26.yaml
  - resource-27.yaml
  - resource-28.yaml
  - resource-29.yaml
  - resource-30.yaml
