---
kind: Role
apiVersion: authorization.openshift.io/v1
metadata:
  name: kvm-device-plugin
  namespace: kvm-device-plugin
rules:
- resources:
  - securitycontextconstraints
  apiGroups:
  - security.openshift.io
  verbs:
  - use
  resourceNames:
  - privileged
