---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sigstore-deploy

resources:
- namespace.yaml

components:
- ../../../../components/project-admin-rolebindings/sigstore
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/small
