apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-octo
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: aws-octo
  dataFrom:
    - extract:
        key: moc/infra/acm/aws-octo
