---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-grafana-public
resources:
  - ../../../base
  - ../common
  - externalsecrets
patchesStrategicMerge:
  - ./grafana-public.yaml
  - ./grafana-route-public.yaml
  - ./servicemonitor.yaml
