kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-annotations-exporter
subjects:
  - kind: ServiceAccount
    name: k8s-annotations-exporter
    namespace: opf-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-reader
