apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kepler-exporter
    spec:
      hostNetwork: true
      serviceAccountName: kepler-sa
      containers:
      - name: kepler-exporter
        image: quay.io/sustainable_computing_io/kepler:operate-first
        imagePullPolicy: Always
        resources:
          requests:
            memory: "400Mi"
            cpu: "100m"
        securityContext:
          privileged: true
        command:
        - /usr/bin/kepler
        - -address
        - 0.0.0.0:9102
        - -enable-gpu=true
        - -enable-cgroup-id=true
        ports:
        - containerPort: 9102
          hostPort: 9102
          name: http
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: tracing
        - name: kernel-src
          mountPath: /usr/src/kernels
        - name: kernel-debug
          mountPath: /sys/kernel/debug
        - mountPath: /proc
          name: proc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: tracing
        hostPath:
          path: /sys
          type: Directory
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: Directory
      - name: kernel-src
        hostPath:
          path: /usr/src/kernels
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
