kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: datahub-linkedin
resources:
    - namespace.yaml
    - resourcequota.yaml
components:
    - ../../../../components/limitranges/default
