apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.smaug.na.operate-first.cloud
        servingCertificate:
          name: api-certificate
