apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: ddas
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: "*"
        operation: All
        resource:
          # this user has access to all topics with "ddas." prefix
          name: ddas.
          patternType: prefix
          type: topic
        type: allow
      - host: "*"
        operation: All
        resource:
          name: ddas
          patternType: literal
          type: group
        type: allow
    type: simple
