apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- ../../cluster-resources
- applications
- externalsecrets
- routes/argocd-google.yaml
configMapGenerator:
- name: argocd-cm
  behavior: replace
  files:
  - configs/argo_cm/dex.config
  - configs/argo_cm/configManagementPlugins
  - configs/argo_cm/globalProjects
  - configs/argo_cm/resource.exclusions
  envs:
  - configs/argo_cm/envs
- name: argocd-rbac-cm
  behavior: replace
  files:
  - configs/argo_rbac_cm/policy.csv
  - configs/argo_rbac_cm/policy.default
generatorOptions:
  disableNameSuffixHash: true
patchesStrategicMerge:
  - serviceaccounts/argocd-dex-server.yaml
