kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: smartoffice
resources:
    - namespace.yaml
components:
    - ../../../../components/limitranges/default
    - ../../../../components/project-admin-rolebindings/rh-dus
    - ../../../../components/resourcequotas/medium
