apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ../../../base
  - ../../common
  - dashboards
  - datasources
patchesStrategicMerge:
  - grafana_oauth_patch.yaml
