apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-kafka-adapter
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  target:
    name: prometheus-kafka-adapter
  dataFrom:
    - extract:
        key: osc/osc-cl2/kafka/prometheus-kafka-adapter

# Vault data should include:
#  KAFKA_BROKER_LIST: ""
#  KAFKA_TOPIC: ""
#  KAFKA_COMPRESSION: ""
#  KAFKA_BATCH_NUM_MESSAGES: ""
#  SERIALIZATION_FORMAT: ""
#  PORT: ""
#  LOG_LEVEL: ""
#  GIN_MODE: ""
