# Source: prometheus-kafka-adapter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-kafka-adapter
  labels:
    app.kubernetes.io/name: prometheus-kafka-adapter
