# Source: prometheus-kafka-adapter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-adapter
  labels:
    app.kubernetes.io/name: prometheus-kafka-adapter
    helm.sh/chart: prometheus-kafka-adapter-0.1.0
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prometheus-kafka-adapter
