---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klusterletaddonconfig-editor
rules:
  - apiGroups:
      - "agent.open-cluster-management.io/v1"
    resources:
      - klusterletaddonconfigs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
