apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-distributed-tracing
resources:
  - ../../base/core/namespaces/openshift-distributed-tracing
  - ../../base/operators.coreos.com/subscriptions/jaeger-operator
  - ../../base/operators.coreos.com/operatorgroups/jaeger-operator
