---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ope
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: 'true'
    opendatahub.io/notebook-image: 'true'
  annotations:
    opendatahub.io/notebook-image-name:
      "Open Education (OPE)"
    opendatahub.io/notebook-image-url:
      "https://github.com/OPEFFORT/ope"
    opendatahub.io/notebook-image-desc:
      "Template Image for Open Education (OPE)"
spec:
  lookupPolicy:
    local: true
  tags:
    - annotations:
        openshift.io/imported-from: quay.io/ope/ope_book
      name: stable-opf
      from:
        kind: DockerImage
        name: 'quay.io/opeffort/ope_book:stable-opf'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Local
