kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
namespace: fedora
resources:
    - namespace.yaml
components:
    - ../../../../components/limitranges/default
    - ../../../../components/project-admin-rolebindings/fedora
    - ../../../../components/resourcequotas/small
