apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
namespace: vault
configMapGenerator:
  - files:
      - taskrun.yaml
    name: backup-vault-run
  - files:
      - scripts/backup-snapshot-to-s3.sh
      - scripts/cleanup-old-taskruns.sh
      - scripts/create-snapshot.sh
      - scripts/prune-old-snapshots.sh
    name: utility-scripts
resources:
  - cronjob.yaml
  - pvc.yaml
  - rolebinding.yaml
  - sa.yaml
  - task.yaml
