# This file should be deployed and managed manually with root creds to s3
# As this is tied to the vault back up job, having this secret managed
# by vault introduces a circular dependency.
apiVersion: v1
kind: Secret
metadata:
  name: backup-job
stringData:
  # Smaug s3 store
  smaug-s3AccessKey: ""  # Add manually
  smaug-s3SecretKey: ""  # Add manually
  smaug-s3BucketName: "opf-vault-snapshots"
  smaug-s3EndPoint: "https://s3-openshift-storage.apps.smaug.na.operate-first.cloud"
  smaug-s3Retention: "1d"

  # Add another s3 store template, replace <bucket-prefix>
  # with a unique value different from the prefixes above
  # this prefix will be passed as an argument to the
  # backup step in the tekton task.

  # <bucket-prefix>-s3AccessKey: ""
  # <bucket-prefix>-s3SecretKey: ""
  # <bucket-prefix>-s3BucketName: ""
  # <bucket-prefix>-s3EndPoint: ""
  # <bucket-prefix>-s3Retention: "1d"

  PVCRetention: "2d"
  OldJobsToKeepCount: "10"
