apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: backup-vault
spec:
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  workspaces:
    - name: snapshots
      mountPath: /snapshots
    - name: backup-job
      mountPath: /backup-job
    - name: utility-scripts
      mountPath: /utility-scripts
  steps:
    # This step creates a snapshot of the vault instance and
    # backs it up to a pvc. Subsequent steps use mc client
    # to mirror contents of this PVC to buckets, as well us
    # pruning data/resources
    - name: create-snapshot
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/create-snapshot.sh'
        - $(workspaces.snapshots.path)
        - $(context.taskRun.namespace)
    # This step cleans the pvc from the previous step of
    # any old data.
    - name: prune-old-snapshots
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      workingDir: /workspace
      command:
        - '/utility-scripts/prune-old-snapshots.sh'
        - $(workspaces.snapshots.path)
    # Clean old jobs, # of jobs to keep is configured in backup config
    # secret.
    - name: cleanup-old-taskruns
      image: quay.io/operate-first/opf-toolbox:v0.8.0
      workingDir: /workspace
      command:
        - '/utility-scripts/cleanup-old-taskruns.sh'

    # Backup data to target s3. Bucket is configured in backup config.
    # Add a similar step for another bucket to back up data to.
    # Update the 3rd argument to match the prefix in the secret.
    - name: backup-snapshot-to-s3-smaug
      image: quay.io/operate-first/mc:RELEASE.2022-06-17T02-52-50Z
      workingDir: /workspace
      command:
        - '/utility-scripts/backup-snapshot-to-s3.sh'
        - $(workspaces.snapshots.path)
        - smaug
