---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: self-provisioners
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: osc-admins
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: drvbw
