apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../../components/project-admin-rolebindings/sigstore-aas
namespace: sigstore-aas
components:
- ../../../../components/limitranges/default
- ../../../../components/resourcequotas/large
