---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  store.thanos.io/shard: shard-0
resources:
  - ../shard-base
patches:
  - target:
      kind: Service
      name: observatorium-thanos-store-shard-base
    patch: |
      - op: replace
        path: /metadata/name
        value: observatorium-thanos-store-shard-0
  - target:
      kind: StatefulSet
      name: observatorium-thanos-store-shard-base
    patch: |
      - op: replace
        path: /metadata/name
        value: observatorium-thanos-store-shard-0
      - op: replace
        path: /spec/serviceName
        value: observatorium-thanos-store-shard-0
