apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: "argocdUrl:"
  service.slack: |
    token: $slack-token
    icon: ":anchor:"
  trigger.on-sync-failed: |
    - when: app.status.operationState.phase in ['Error', 'Failed']
      description: Application syncing has failed
      send: [app-sync-failed]
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase in ['Succeeded']
      description: Application syncing has succeeded
      send: [app-sync-succeeded]
      oncePer: app.status.sync.revision
  trigger.on-sync-status-unknown: |
    - when: app.status.sync.status == 'Unknown'
      description: Application status is 'Unknown'
      send: [app-sync-status-unknown]
  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      description: Application has degraded
      send: [app-health-degraded]
  trigger.on-sync-running: |
    - when: app.status.operationState.phase in ['Running']
      description: Application is being synced
      send: [app-sync-running]
      oncePer: app.status.sync.revision
  template.app-sync-failed: |
    message: |
      {{if eq .serviceType "slack"}}:x:{{end}}  The sync operation of application {{.app.metadata.name}} has failed at {{.app.status.operationState.finishedAt}} with the following error: {{.app.status.operationState.message}}
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
    slack:
      attachments: |
        [{
          "title": "Git information: {{ .app.metadata.name}}",
          "color": "#ffffff",
          "fields": [
            {
              "title": "Target Branch: ",
              "value": "{{.app.spec.source.targetRevision}}",
              "short": true
            },
            {
              "title": "Repository: ",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Overlay Path: ",
              "value": "{{.app.spec.source.path}}"
            },
            {
              "title": "Revision: ",
              "value": "{{.app.status.sync.revision}}"
            }
          ]
        }]
      notifyBroadcast: true
      groupingKey: "{{.app.status.sync.revision}}"
  template.app-sync-succeeded: |
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
    slack:
      attachments: |
        [{
          "title": "Git information: {{ .app.metadata.name}}",
          "color": "#ffffff",
          "fields": [
            {
              "title": "Target Branch: ",
              "value": "{{.app.spec.source.targetRevision}}",
              "short": true
            },
            {
              "title": "Repository: ",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Overlay Path: ",
              "value": "{{.app.spec.source.path}}"
            },
            {
              "title": "Revision: ",
              "value": "{{.app.status.sync.revision}}"
            }
          ]
        }]
      notifyBroadcast: false
      groupingKey: "{{.app.status.sync.revision}}"
  template.app-sync-status-unknown: |
    message: |
      {{if eq .serviceType "slack"}}:exclamation:{{end}} Application {{.app.metadata.name}} sync is 'Unknown'.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      attachments: |
        [{
          "title": "Git information: {{ .app.metadata.name}}",
          "color": "#ffffff",
          "fields": [
            {
              "title": "Target Branch: ",
              "value": "{{.app.spec.source.targetRevision}}",
              "short": true
            },
            {
              "title": "Repository: ",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Overlay Path: ",
              "value": "{{.app.spec.source.path}}"
            },
            {
              "title": "Revision: ",
              "value": "{{.app.status.sync.revision}}"
            }
          ]
        }]
      notifyBroadcast: true
      groupingKey: "{{.app.status.sync.revision}}"
  template.app-health-degraded: |
    message: |
      {{if eq .serviceType "slack"}}:small_red_triangle_down:{{end}} Application {{.app.metadata.name}} has degraded.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      attachments: |
        [{
          "title": "Git information: {{ .app.metadata.name}}",
          "color": "#ffffff",
          "fields": [
            {
              "title": "Target Branch: ",
              "value": "{{.app.spec.source.targetRevision}}",
              "short": true
            },
            {
              "title": "Repository: ",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Overlay Path: ",
              "value": "{{.app.spec.source.path}}"
            },
            {
              "title": "Revision: ",
              "value": "{{.app.status.sync.revision}}"
            }
          ]
        }]
      notifyBroadcast: true
      groupingKey: "{{.app.status.sync.revision}}"
  template.app-sync-running: |
    message: |
      The sync operation of application {{.app.metadata.name}} has started at {{.app.status.operationState.startedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
    slack:
      attachments: |
        [{
          "title": "Git information: {{ .app.metadata.name}}",
          "color": "#ffffff",
          "fields": [
            {
              "title": "Target Branch: ",
              "value": "{{.app.spec.source.targetRevision}}",
              "short": true
            },
            {
              "title": "Repository: ",
              "value": "{{.app.spec.source.repoURL}}",
              "short": true
            },
            {
              "title": "Overlay Path: ",
              "value": "{{.app.spec.source.path}}"
            },
            {
              "title": "Revision: ",
              "value": "{{.app.status.sync.revision}}"
            }
          ]
        }]
      notifyBroadcast: false
      groupingKey: "{{.app.status.sync.revision}}"
