---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-observatorium
commonLabels:
  app.kubernetes.io/part-of: observatorium
  app.kubernetes.io/name: thanos
resources:
  - ../../../../base/instance/thanos
  - deployments
  - externalsecrets
  - horizontalpodautoscalers
  - rolebindings
  - roles
  - routes
  - serviceaccounts
  - servicemonitors
  - services
  - obcs
