apiVersion: v1
kind: ResourceQuota
metadata:
  name: sostrades-resourcequota-custom
spec:
  hard:
    limits.cpu: '30'
    limits.memory: 100Gi
    requests.cpu: '6'
    requests.memory: 10Gi
    requests.storage: 100Gi
    count/objectbucketclaims.objectbucket.io: "1"
