---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../../../../components/project-admin-rolebindings/adoptium
- ../../../../components/resourcequotas/large
- ../../../../components/limitranges/default

namespace: adoptium-project

resources:
- namespace.yaml
