apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: store
  name: observatorium-thanos-store-shard-base
spec:
  clusterIP: None
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  selector:
    app.kubernetes.io/component: store
