kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kepler-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowHostIPC: true
allowHostPID: true
readOnlyRootFilesystem: true
defaultAddCapabilities:
- SYS_ADMIN
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
volumes:
  - configMap
  - emptyDir
  - hostPath
  - projected
users:
  - system:serviceaccount:kepler-monitoring:kepler-sa
