apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-monitoring
resources:
  - ../../base/operators.coreos.com/operatorgroups/opf-monitoring
  - ../../base/operators.coreos.com/subscriptions/grafana-operator
