apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: entities
  description: A collection of all the service catalog entities
spec:
  targets:
    - ./apis.yaml
    - ./components.yaml
    - ./domains.yaml
    - ./groups.yaml
    - ./resources.yaml
    - ./systems.yaml
    - ./users.yaml
