apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: "argocd-notifications"
    notifications.argoproj.io/subscribe.on-sync-running.slack: "argocd-notifications"
    notifications.argoproj.io/subscribe.on-sync-failed.slack: "argocd-notifications"
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: "argocd-notifications"
    notifications.argoproj.io/subscribe.on-sync-degraded.slack: "argocd-notifications"
spec:
  destination:
    name: smaug
    namespace: open-cluster-management-agent
  ignoreDifferences:
    - group: imageregistry.operator.openshift.io
      jsonPointers:
        - /spec/defaultRoute
        - /spec/httpSecret
        - /spec/proxy
        - /spec/requests
        - /spec/rolloutStrategy
      kind: Config
      name: cluster
    - group: apps
      jsonPointers:
        - /spec/template/spec/containers/0/image
      kind: DaemonSet
      name: kvm-device-plugin
  project: cluster-management
  source:
    path: cluster-scope/overlays/prod/moc/smaug
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #   - Validate=false
  #   - ApplyOutOfSyncOnly=true
