apiVersion: v1
stringData:
  AIRFLOW_EMAIL: admin@admin.com
  AIRFLOW_FNAME: admin
  AIRFLOW_LNAME: admin
  AIRFLOW_PASSWORD: admin
  AIRFLOW_ROLE: Admin
  AIRFLOW_USERNAME: admin
kind: Secret
metadata:
  name: airflow-secrets
type: Opaque
