apiVersion: v1
stringData:
  init_airflow_db_scripts.sql: |
    CREATE DATABASE airflow_db;
    CREATE USER 'airflow'@'%' IDENTIFIED BY 'testpassword1';
    GRANT ALL PRIVILEGES ON airflow_db.* TO 'airflow'@'%' WITH GRANT OPTION;
    commit;

  init_openmetadata_db_scripts.sql: |
    CREATE DATABASE openmetadata_db;
    CREATE USER 'openmetadata_user'@'%' IDENTIFIED BY 'testpassword2';
    GRANT ALL PRIVILEGES ON openmetadata_db.* TO 'openmetadata_user'@'%' WITH GRANT OPTION;
    commit;

kind: Secret
metadata:
  name: mysql-init-scripts
type: Opaque
