apiVersion: v1
stringData:
  AIRFLOW_DB: airflow_db
  AIRFLOW_DB_PASSWORD: testpassword1
  AIRFLOW_DB_USER: airflow
  OPENMETADATA_DB: openmetadata_db
  OPENMETADATA_DB_PASSWORD: testpassword2
  OPENMETADATA_DB_USER: openmetadata_user
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
