apiVersion: v1
stringData:
  # Test keys
  AIRFLOW__CORE__FERNET_KEY: BfLzDb8P7HcF0LeZMCjIkcaJ6pXi2rxsBIGJoTffqJk=
  AIRFLOW__WEBSERVER__SECRET_KEY: 38fe94df-115c-4096-91ec-b6e16ce3a01f
kind: Secret
metadata:
  name: openmetadata-dependencies-config-envs
type: Opaque
