# This policy is designed to be CPU-BOUND for performance testing.
# It uses the user's superior logic to run a complex regex against a
# field that is guaranteed to exist on all Kubernetes resources (`apiVersion`).

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: force-cpu-per-resource
  annotations:
    policies.kyverno.io/title: Force CPU Burn Per Resource
    policies.kyverno.io/category: Benchmarking
    policies.kyverno.io/subject: All Resources
    policies.kyverno.io/description: >-
      This is a benchmarking tool. It consumes CPU cycles by running a complex
      regex known for 'catastrophic backtracking' against the apiVersion
      of every resource. This is guaranteed to run without causing errors.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: run-complex-regex-per-resource
      match:
        any:
          - resources:
              # This match block is truly universal.
              kinds:
                - "*"
              apiGroups:
                - "*"
      validate:
        message: "Forcing CPU-intensive regex for resource."
        deny:
          conditions:
            any:
              - key: "{{ request.object.apiVersion }}"
                operator: NotMatchesRegex
                value: "^([a-z0-9](-?[a-z0-9])*.?)+$"