# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: force-cpu-per-resource
  annotations:
    policies.kyverno.io/title: Force CPU Burn Per Resource
    policies.kyverno.io/category: Benchmarking
    policies.kyverno.io/subject: All Resources
    policies.kyverno.io/description: >-
      This is a benchmarking tool. It consumes CPU cycles by running a complex
      regex known for 'catastrophic backtracking' against the kind
      of every resource.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: run-complex-regex-per-resource
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
                - ConfigMap
                - Secret
                - CronJob
                - Service
                - Namespace
                - OCIRepository
                - Job
                - StatefulSet
                - DaemonSet
                - Ingress
                - Role
                - RoleBinding
                - ClusterRole
                - ClusterRoleBinding
                - ClusterSecretStore
                - ReplicationSource
                - ReplicationDestination
                - Provider
                - GitRepository
                - PersistentVolumeClaim
                - NetworkPolicy
      validate:
        message: "Forcing CPU-intensive regex for resource."
        deny:
          conditions:
            any:
              - key: "{{ kind }}"
                operator: NotMatchesRegex
                # This complex regex forces the engine to do a lot of work.
                value: "^([a-z0-9](-?[a-z0-9])*.?)+$"