# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-burn-via-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: cpu-burn-labels
      match:
        any:
          - resources:
              kinds:
                - "*"  # Apply to all resources
      preconditions:
        all:
          - key: "{{ request.object.metadata.labels }}"
            operator: Defined
      validate:
        message: "Simulating CPU burn via regex over label keys."
        foreach:
          - list: "request.object.metadata.labels"
            deny:
              conditions:
                all:
                  - key: "{{ element.key }}"
                    operator: NotMatchesRegex
                    # Costly regex for benchmarking
                    value: "^([a-z0-9](-?[a-z0-9])*.?)+$"