# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-burn-via-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: cpu-burn-labels
      match:
        any:
          - resources:
              kinds:
                - Deployment
      preconditions:
        all:
          - key: "{{ resource.metadata.labels }}"
            operator: Defined
      validate:
        message: "Simulating CPU burn via regex over label keys."
        foreach:
          - list: "keys(resource.metadata.labels)"
            deny:
              conditions:
                all:
                  - key: "{{ element }}"
                    operator: NotMatchesRegex
                    # This is an intentionally expensive regex (catastrophic backtracking).
                    value: "^([a-z0-9](-?[a-z0-9])*.?)+$"