# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-burn-via-labels
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: cpu-burn-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
                - ConfigMap
                - Secret
                - CronJob
                - Service
                - Namespace
                - Job
                - StatefulSet
                - DaemonSet
                - Ingress
      preconditions:
        all:
          - key: "{{ resource.metadata.labels }}"
            operator: Defined
      validate:
        message: "Simulating CPU burn via regex over label keys."
        foreach:
          - list: "resource.metadata.labels"
            context:
              - name: labelKey
                variable:
                  jmesPath: "key"
            deny:
              conditions:
                all:
                  - key: "{{ labelKey }}"
                    operator: NotMatchesRegex
                    value: "^([a-z0-9](-?[a-z0-9])*.?)+$"