# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-burn-container-name
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: burn-cpu-via-container-name
      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
                - ConfigMap
                - Secret
                - CronJob
                - Service
                - Namespace
                - OCIRepository
                - Job
                - StatefulSet
                - DaemonSet
                - Ingress
                - Role
                - RoleBinding
                - ClusterRole
                - ClusterRoleBinding
                - ClusterSecretStore
                - ReplicationSource
                - ReplicationDestination
                - Provider
                - GitRepository
                - PersistentVolumeClaim
                - NetworkPolicy
      validate:
        message: "Simulating CPU load on container names."
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                all:
                  - key: "{{ element.name }}"
                    operator: NotMatchesRegex
                    value: "^([a-z0-9](-?[a-z0-9])*.?)+$"  # deliberately inefficient regex