# This policy is designed to be CPU-BOUND for performance testing.
# It runs a complex regex against a field that is guaranteed to exist on every resource.
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cpu-burn-via-name
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: cpu-burn-name
      match:
        any:
          - resources:
              kinds:
                - Deployment
      validate:
        message: "Simulating CPU burn via complex regex on metadata.name."
        deny:
          conditions:
            all:
              - key: "{{ request.object.metadata.name }}"
                operator: NotMatchesRegex
                value: "^([a-z0-9](-?[a-z0-9])*.?)+$"