# This policy is designed to be CPU-BOUND for performance testing.
# It forces Kyverno to perform a computationally expensive Regex match for
# every single resource processed by the `apply` command.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: force-cpu-per-resource
  annotations:
    policies.kyverno.io/title: Force CPU Burn Per Resource
    policies.kyverno.io/category: Benchmarking
    policies.kyverno.io/subject: All Resources
    policies.kyverno.io/description: >-
      This is a benchmarking tool. It consumes CPU cycles by running a complex
      regex known for 'catastrophic backtracking' against the metadata name
      of every resource.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: run-complex-regex-per-resource
      match:
        any:
          - resources:
              kinds:
                - "*"
      preconditions:
        all:
          - key: "{{ request.object.metadata.name || '' }}"
            operator: NotEquals
            value: ""
      validate:
        message: "Forcing CPU-intensive regex for resource {{ request.object.kind | default('unknown-kind') }}/{{ request.object.metadata.name | default('unknown-name') }}."
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.name }}"
                # We use NotMatchesRegex because this complex pattern will likely not match,
                # which means the rule result will be 'pass'. However, the regex engine
                # MUST still perform the full, expensive evaluation before it can determine this.
                operator: NotMatchesRegex
                # --- THIS IS THE FIX ---
                # This new regex is significantly more complex. The nested quantifiers
                # (e.g., the '+' inside the '*') force the regex engine to try an
                # exponential number of possibilities, consuming a large amount of CPU.
                value: "^([a-z0-9](-?[a-z0-9])*.?)+$"