# This policy is designed to be CPU-BOUND for performance testing.
# It forces Kyverno to perform a computationally expensive Regex match for
# every single resource processed by the `apply` command.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: force-cpu-per-resource
  annotations:
    policies.kyverno.io/title: Force CPU Burn Per Resource
    policies.kyverno.io/category: Benchmarking
    policies.kyverno.io/subject: All Resources
    policies.kyverno.io/description: >-
      This is a benchmarking tool. It consumes CPU cycles by running a complex
      regex known for 'catastrophic backtracking' against the metadata name
      of every resource.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: run-complex-regex-per-resource
      match:
        any:
          - resources:
              kinds:
                - "*"
      # --- THIS IS THE FIX ---
      # This precondition block acts as a guard. It ensures the rule only runs on
      # resources that have a metadata.name field, preventing errors.
      preconditions:
        all:
          - key: "{{ request.object.metadata.name || '' }}"
            operator: NotEquals
            value: ""
      # --- END OF FIX ---
      validate:
        message: "Forcing CPU-intensive regex for resource {{request.object.kind}}/{{request.object.metadata.name}}."
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.name }}"
                operator: MatchesRegex
                value: "([a-zA-Z]+s)*$"
