# This policy is designed to be I/O-BOUND for performance testing.
# It forces Kyverno to make a separate, external HTTP GET request for
# every single resource processed by the `apply` command.

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: force-io-per-resource-alpha
  annotations:
    policies.kyverno.io/title: Force I/O Wait Per Resource
    policies.kyverno.io/category: Benchmarking
    policies.kyverno.io/subject: All Resources
    policies.kyverno.io/description: >-
      This is a benchmarking tool. It forces network latency by making an
      external API call for every resource, allowing for clear measurement
      of I/O-bound policy performance.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: call-external-api-per-resource
      match:
        any:
          - resources:
              kinds:
                - "*"
      # --- THIS IS THE DEFINITIVE FIX ---
      # This precondition block safely checks for the existence of each key in the path
      # before trying to use it. This prevents variable resolution errors on resources
      # that do not have a standard metadata structure.
      preconditions:
        all:
          - key: "{{ request.object.keys(@) || [] }}"
            operator: AnyIn
            value: ["metadata"]
          - key: "{{ request.object.metadata.keys(@) || [] }}"
            operator: AnyIn
            value: ["name"]
      # --- END OF FIX ---
      context:
        - name: externalApiData
          apiCall:
            urlPath: "https://catfact.ninja/fact"
            jmesPath: "fact"
      validate:
        message: "Forcing I/O wait for resource."
        pattern:
          context:
            externalApiData: "?*"