apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: validate-configmap-annotation-and-data
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-data-key-for-annotation
      # 1. Match the correct resource: ConfigMap.
      match:
        any:
          - resources:
              kinds:
                - ConfigMap
      preconditions:
        all:
          - key: "{{ request.object.keys(@) || [] }}"
            operator: AnyIn
            value: ["metadata"]
          - key: "{{ request.object.keys(@) || [] }}"
            operator: AnyIn
            value: ["data"]
          - key: "{{ request.object.metadata.keys(@) || [] }}"
            operator: AnyIn
            value: ["annotations"]
          - key: "{{ request.object.metadata.keys(@) || [] }}"
            operator: AnyIn
            value: ["name"]
      validate:
        message: "ConfigMap is missing required data key for annotation ."
        # 2. Iterate over all annotation keys. The '|| ``{}``' makes it safe.
        foreach:
          - list: "keys(request.object.metadata.annotations || `{}`)"
            # 3. Use a precondition to only act on the keys we care about.
            # 4. Deny if the condition is met.
            deny:
              conditions:
                any:

                  - key: "{{ element }}"
                    operator: NotEquals
                    value: "*/key-*"

                  - key: "{{ element }}"
                    operator: Equals
                    value: "foo"
                  - key: "{{ request.object.metadata.annotations.\"{{element}}\" }}"
                    operator: Equals
                    value: "bar"
                  - key: "{{ contains(element, 'will-not-be-found') }}"
                    operator: Equals
                    value: true
                  - key: "{{ contains(request.object.metadata.annotations.\"{{element}}\", 'another-string-that-is-not-present') }}"
                    operator: Equals
                    value: true
                  - key: "{{ length(element) }}"
                    operator: Equals
                    value: "1"