apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  template:
    spec:
      containers:
      - name: dex
        env:
        - name: DEX_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: argocd-dex-server-oauth-token
              key: token
