apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          env:
            - name: GNUPGHOME
              value: /home/argocd/.gnupg
          volumeMounts:
            - name: key
              mountPath: /key
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "gpg --import /key/*"]
          # This is so we can run the lifecycle poststart cmd w/o issues
          securityContext:
            readOnlyRootFilesystem: false
      volumes:
        - name: key
          secret:
            secretName: ksops-pgp-key
