apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../../../components/project-admin-rolebindings/lotus
- resourcequota.yaml
namespace: lotus
components:
- ../../../../components/limitranges/default
