apiVersion: v1
kind: ResourceQuota
metadata:
  name: lotus
spec:
  hard:
    limits.cpu: 6
    limits.memory: 48Gi
    requests.cpu: 4
    requests.memory: 32Gi
    requests.storage: 2048Gi
    count/objectbucketclaims.objectbucket.io: 1
