---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opf-observatorium
commonLabels:
  app.kubernetes.io/part-of: observatorium
  app.kubernetes.io/name: loki
resources:
  - ../../../../base/instance/loki
  - externalsecrets
  - servicemonitors
  - obcs

patchesStrategicMerge:
  - configmaps/observatorium-loki-configmap_patch.yaml
