apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- resourcequota.yaml
namespace: thoth-cre-integration
components:
- ../../../../components/project-admin-rolebindings/thoth
- ../../../../components/limitranges/default
