apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  labels:
    custom-crio: high-pid-limit
  name: osc-platform
spec:
  machineConfigSelector:
    matchExpressions:
      - key: machineconfiguration.openshift.io/role
        operator: In
        values:
          - worker
          - osc-platform
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/osc-platform: ''
