apiVersion: v1
kind: ResourceQuota
metadata:
  name: sdap-mslsp-custom
spec:
  hard:
    limits.cpu: '16'
    limits.memory: 64Gi
    requests.cpu: '16'
    requests.memory: 64Gi
    requests.storage: 80Gi
