---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kvm-device-plugin
  namespace: kvm-device-plugin
  labels:
    app: kvm-device-plugin
spec:
  lookupPolicy:
    local: true
  tags:
  - name: latest
    referencePolicy:
      type: Source
