apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: store-bucket-cache
  name: observatorium-thanos-store-bucket-cache-memcached
spec:
  clusterIP: None
  ports:
  - name: client
    port: 11211
    targetPort: 11211
  - name: metrics
    port: 9150
    targetPort: 9150
  selector:
    app.kubernetes.io/component: store-bucket-cache
