apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  audit:
    profile: Default
  servingCerts:
    namedCertificates:
      - names:
          - api.odh-cl1.apps.os-climate.org
        servingCertificate:
          name: api-certs
