apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-catalog-k8s-plugin-tokens
  namespace: service-catalog
spec:
  secretStoreRef:
    name: opf-vault-store
    kind: SecretStore
  refreshInterval: "1h"
  target:
    name: service-catalog-k8s-plugin-tokens
  dataFrom:
    - extract:
        key: moc/smaug/service-catalog/k8s-plugin-tokens
