kind: LimitRange
apiVersion: v1
metadata:
  name: default
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 200Mi
      defaultRequest:
        cpu: 100m
        memory: 100Mi
