apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
spec:
  destination:
    name: moc-infra
    namespace: argocd
  project: cluster-management
  source:
    path: argocd-notifications/overlays/infra
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  #   syncOptions:
  #     - Validate=false
