kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-interceptor-opf-ci-pipelines
subjects:
  - kind: ServiceAccount
    name: aicoe-ci-webhook
    namespace: opf-ci-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-pipelines-clusterinterceptors
